# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python_proto/claude/claude.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n python_proto/claude/claude.proto\x12\x06\x63laude\"\xaa\x01\n\x19\x45valuationRequestToClaude\x12\x18\n\x10student_response\x18\x01 \x01(\t\x12\x0f\n\x07passage\x18\x02 \x01(\t\x12\x10\n\x08question\x18\x03 \x01(\t\x12\x19\n\x11\x63omplex_sentences\x18\x04 \x01(\t\x12\x1b\n\x13\x61\x64vanced_vocabulary\x18\x05 \x01(\t\x12\x18\n\x10\x63ohesive_devices\x18\x06 \x01(\t\"2\n\x1c\x45valuationResponseFromClaude\x12\x12\n\nevaluation\x18\x01 \x01(\t\"\xd1\x01\n EvaluationResponseFromToDataBase\x12\x18\n\x10student_response\x18\x01 \x01(\t\x12\x0f\n\x07passage\x18\x02 \x01(\t\x12\x10\n\x08question\x18\x03 \x01(\t\x12\x19\n\x11\x63omplex_sentences\x18\x04 \x01(\t\x12\x1b\n\x13\x61\x64vanced_vocabulary\x18\x05 \x01(\t\x12\x18\n\x10\x63ohesive_devices\x18\x06 \x01(\t\x12\x1e\n\x16\x65valuation_from_claude\x18\x07 \x01(\t2u\n\x0cIELTSService\x12\x65\n\rEvaluateIELTS\x12(.claude.EvaluationResponseFromToDataBase\x1a(.claude.EvaluationResponseFromToDataBase\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'python_proto.claude.claude_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVALUATIONREQUESTTOCLAUDE._serialized_start=45
  _EVALUATIONREQUESTTOCLAUDE._serialized_end=215
  _EVALUATIONRESPONSEFROMCLAUDE._serialized_start=217
  _EVALUATIONRESPONSEFROMCLAUDE._serialized_end=267
  _EVALUATIONRESPONSEFROMTODATABASE._serialized_start=270
  _EVALUATIONRESPONSEFROMTODATABASE._serialized_end=479
  _IELTSSERVICE._serialized_start=481
  _IELTSSERVICE._serialized_end=598
# @@protoc_insertion_point(module_scope)
