// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testGuests(t *testing.T) {
	t.Parallel()

	query := Guests()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testGuestsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGuestsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Guests().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGuestsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GuestSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGuestsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := GuestExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Guest exists: %s", err)
	}
	if !e {
		t.Errorf("Expected GuestExists to return true, but got false.")
	}
}

func testGuestsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	guestFound, err := FindGuest(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if guestFound == nil {
		t.Error("want a record, got nil")
	}
}

func testGuestsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Guests().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testGuestsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Guests().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testGuestsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	guestOne := &Guest{}
	guestTwo := &Guest{}
	if err = randomize.Struct(seed, guestOne, guestDBTypes, false, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}
	if err = randomize.Struct(seed, guestTwo, guestDBTypes, false, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = guestOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = guestTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Guests().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testGuestsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	guestOne := &Guest{}
	guestTwo := &Guest{}
	if err = randomize.Struct(seed, guestOne, guestDBTypes, false, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}
	if err = randomize.Struct(seed, guestTwo, guestDBTypes, false, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = guestOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = guestTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func guestBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func testGuestsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Guest{}
	o := &Guest{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, guestDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Guest object: %s", err)
	}

	AddGuestHook(boil.BeforeInsertHook, guestBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	guestBeforeInsertHooks = []GuestHook{}

	AddGuestHook(boil.AfterInsertHook, guestAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	guestAfterInsertHooks = []GuestHook{}

	AddGuestHook(boil.AfterSelectHook, guestAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	guestAfterSelectHooks = []GuestHook{}

	AddGuestHook(boil.BeforeUpdateHook, guestBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	guestBeforeUpdateHooks = []GuestHook{}

	AddGuestHook(boil.AfterUpdateHook, guestAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	guestAfterUpdateHooks = []GuestHook{}

	AddGuestHook(boil.BeforeDeleteHook, guestBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	guestBeforeDeleteHooks = []GuestHook{}

	AddGuestHook(boil.AfterDeleteHook, guestAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	guestAfterDeleteHooks = []GuestHook{}

	AddGuestHook(boil.BeforeUpsertHook, guestBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	guestBeforeUpsertHooks = []GuestHook{}

	AddGuestHook(boil.AfterUpsertHook, guestAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	guestAfterUpsertHooks = []GuestHook{}
}

func testGuestsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGuestsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(guestPrimaryKeyColumns, guestColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGuestToManyDeliveries(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Guest
	var b, c Delivery

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, deliveryDBTypes, false, deliveryColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, deliveryDBTypes, false, deliveryColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.GuestID, a.ID)
	queries.Assign(&c.GuestID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Deliveries().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.GuestID, b.GuestID) {
			bFound = true
		}
		if queries.Equal(v.GuestID, c.GuestID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := GuestSlice{&a}
	if err = a.L.LoadDeliveries(ctx, tx, false, (*[]*Guest)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Deliveries); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Deliveries = nil
	if err = a.L.LoadDeliveries(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Deliveries); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testGuestToManyOrders(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Guest
	var b, c Order

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, orderDBTypes, false, orderColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, orderDBTypes, false, orderColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.GuestID, a.ID)
	queries.Assign(&c.GuestID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Orders().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.GuestID, b.GuestID) {
			bFound = true
		}
		if queries.Equal(v.GuestID, c.GuestID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := GuestSlice{&a}
	if err = a.L.LoadOrders(ctx, tx, false, (*[]*Guest)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Orders); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Orders = nil
	if err = a.L.LoadOrders(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Orders); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testGuestToManyAddOpDeliveries(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Guest
	var b, c, d, e Delivery

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, guestDBTypes, false, strmangle.SetComplement(guestPrimaryKeyColumns, guestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Delivery{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, deliveryDBTypes, false, strmangle.SetComplement(deliveryPrimaryKeyColumns, deliveryColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Delivery{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddDeliveries(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.GuestID) {
			t.Error("foreign key was wrong value", a.ID, first.GuestID)
		}
		if !queries.Equal(a.ID, second.GuestID) {
			t.Error("foreign key was wrong value", a.ID, second.GuestID)
		}

		if first.R.Guest != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Guest != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Deliveries[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Deliveries[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Deliveries().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testGuestToManySetOpDeliveries(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Guest
	var b, c, d, e Delivery

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, guestDBTypes, false, strmangle.SetComplement(guestPrimaryKeyColumns, guestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Delivery{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, deliveryDBTypes, false, strmangle.SetComplement(deliveryPrimaryKeyColumns, deliveryColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetDeliveries(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Deliveries().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetDeliveries(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Deliveries().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.GuestID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.GuestID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.GuestID) {
		t.Error("foreign key was wrong value", a.ID, d.GuestID)
	}
	if !queries.Equal(a.ID, e.GuestID) {
		t.Error("foreign key was wrong value", a.ID, e.GuestID)
	}

	if b.R.Guest != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Guest != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Guest != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Guest != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.Deliveries[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Deliveries[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testGuestToManyRemoveOpDeliveries(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Guest
	var b, c, d, e Delivery

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, guestDBTypes, false, strmangle.SetComplement(guestPrimaryKeyColumns, guestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Delivery{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, deliveryDBTypes, false, strmangle.SetComplement(deliveryPrimaryKeyColumns, deliveryColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddDeliveries(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Deliveries().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveDeliveries(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Deliveries().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.GuestID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.GuestID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Guest != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Guest != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Guest != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Guest != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.Deliveries) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Deliveries[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Deliveries[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testGuestToManyAddOpOrders(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Guest
	var b, c, d, e Order

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, guestDBTypes, false, strmangle.SetComplement(guestPrimaryKeyColumns, guestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Order{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, orderDBTypes, false, strmangle.SetComplement(orderPrimaryKeyColumns, orderColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Order{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddOrders(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.GuestID) {
			t.Error("foreign key was wrong value", a.ID, first.GuestID)
		}
		if !queries.Equal(a.ID, second.GuestID) {
			t.Error("foreign key was wrong value", a.ID, second.GuestID)
		}

		if first.R.Guest != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Guest != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Orders[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Orders[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Orders().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testGuestToManySetOpOrders(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Guest
	var b, c, d, e Order

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, guestDBTypes, false, strmangle.SetComplement(guestPrimaryKeyColumns, guestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Order{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, orderDBTypes, false, strmangle.SetComplement(orderPrimaryKeyColumns, orderColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetOrders(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Orders().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetOrders(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Orders().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.GuestID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.GuestID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.GuestID) {
		t.Error("foreign key was wrong value", a.ID, d.GuestID)
	}
	if !queries.Equal(a.ID, e.GuestID) {
		t.Error("foreign key was wrong value", a.ID, e.GuestID)
	}

	if b.R.Guest != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Guest != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Guest != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Guest != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.Orders[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Orders[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testGuestToManyRemoveOpOrders(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Guest
	var b, c, d, e Order

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, guestDBTypes, false, strmangle.SetComplement(guestPrimaryKeyColumns, guestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Order{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, orderDBTypes, false, strmangle.SetComplement(orderPrimaryKeyColumns, orderColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddOrders(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Orders().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveOrders(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Orders().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.GuestID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.GuestID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Guest != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Guest != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Guest != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Guest != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.Orders) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Orders[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Orders[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testGuestToOneBranchUsingBranch(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Guest
	var foreign Branch

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, branchDBTypes, false, branchColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Branch struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.BranchID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Branch().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddBranchHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Branch) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := GuestSlice{&local}
	if err = local.L.LoadBranch(ctx, tx, false, (*[]*Guest)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Branch == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Branch = nil
	if err = local.L.LoadBranch(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Branch == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testGuestToOneTableUsingTableNumberTable(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Guest
	var foreign Table

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, tableDBTypes, false, tableColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Table struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.TableNumber, foreign.Number)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.TableNumberTable().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.Number, foreign.Number) {
		t.Errorf("want: %v, got %v", foreign.Number, check.Number)
	}

	ranAfterSelectHook := false
	AddTableHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Table) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := GuestSlice{&local}
	if err = local.L.LoadTableNumberTable(ctx, tx, false, (*[]*Guest)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.TableNumberTable == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.TableNumberTable = nil
	if err = local.L.LoadTableNumberTable(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.TableNumberTable == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testGuestToOneSetOpBranchUsingBranch(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Guest
	var b, c Branch

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, guestDBTypes, false, strmangle.SetComplement(guestPrimaryKeyColumns, guestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, branchDBTypes, false, strmangle.SetComplement(branchPrimaryKeyColumns, branchColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, branchDBTypes, false, strmangle.SetComplement(branchPrimaryKeyColumns, branchColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Branch{&b, &c} {
		err = a.SetBranch(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Branch != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Guests[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.BranchID, x.ID) {
			t.Error("foreign key was wrong value", a.BranchID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.BranchID))
		reflect.Indirect(reflect.ValueOf(&a.BranchID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.BranchID, x.ID) {
			t.Error("foreign key was wrong value", a.BranchID, x.ID)
		}
	}
}

func testGuestToOneRemoveOpBranchUsingBranch(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Guest
	var b Branch

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, guestDBTypes, false, strmangle.SetComplement(guestPrimaryKeyColumns, guestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, branchDBTypes, false, strmangle.SetComplement(branchPrimaryKeyColumns, branchColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetBranch(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveBranch(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Branch().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Branch != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.BranchID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.Guests) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testGuestToOneSetOpTableUsingTableNumberTable(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Guest
	var b, c Table

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, guestDBTypes, false, strmangle.SetComplement(guestPrimaryKeyColumns, guestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, tableDBTypes, false, strmangle.SetComplement(tablePrimaryKeyColumns, tableColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, tableDBTypes, false, strmangle.SetComplement(tablePrimaryKeyColumns, tableColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Table{&b, &c} {
		err = a.SetTableNumberTable(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.TableNumberTable != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.TableNumberGuests[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.TableNumber, x.Number) {
			t.Error("foreign key was wrong value", a.TableNumber)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TableNumber))
		reflect.Indirect(reflect.ValueOf(&a.TableNumber)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.TableNumber, x.Number) {
			t.Error("foreign key was wrong value", a.TableNumber, x.Number)
		}
	}
}

func testGuestToOneRemoveOpTableUsingTableNumberTable(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Guest
	var b Table

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, guestDBTypes, false, strmangle.SetComplement(guestPrimaryKeyColumns, guestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, tableDBTypes, false, strmangle.SetComplement(tablePrimaryKeyColumns, tableColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetTableNumberTable(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveTableNumberTable(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.TableNumberTable().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.TableNumberTable != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.TableNumber) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.TableNumberGuests) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testGuestsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGuestsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GuestSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGuestsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Guests().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	guestDBTypes = map[string]string{`ID`: `bigint`, `BranchID`: `bigint`, `Name`: `character varying`, `TableNumber`: `integer`, `RefreshToken`: `character varying`, `RefreshTokenExpiresAt`: `timestamp with time zone`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`, `DeletedAt`: `timestamp with time zone`}
	_            = bytes.MinRead
)

func testGuestsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(guestPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(guestAllColumns) == len(guestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, guestDBTypes, true, guestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testGuestsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(guestAllColumns) == len(guestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, guestDBTypes, true, guestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(guestAllColumns, guestPrimaryKeyColumns) {
		fields = guestAllColumns
	} else {
		fields = strmangle.SetComplement(
			guestAllColumns,
			guestPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := GuestSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testGuestsUpsert(t *testing.T) {
	t.Parallel()

	if len(guestAllColumns) == len(guestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Guest{}
	if err = randomize.Struct(seed, &o, guestDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Guest: %s", err)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, guestDBTypes, false, guestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Guest: %s", err)
	}

	count, err = Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
