// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Accounts", testAccountsUpsert)

	t.Run("Branches", testBranchesUpsert)

	t.Run("Deliveries", testDeliveriesUpsert)

	t.Run("DeliveryDishes", testDeliveryDishesUpsert)

	t.Run("DishPriceHistories", testDishPriceHistoriesUpsert)

	t.Run("Dishes", testDishesUpsert)

	t.Run("Guests", testGuestsUpsert)

	t.Run("OrderDishes", testOrderDishesUpsert)

	t.Run("OrderSets", testOrderSetsUpsert)

	t.Run("Orders", testOrdersUpsert)

	t.Run("Regulations", testRegulationsUpsert)

	t.Run("SetDishes", testSetDishesUpsert)

	t.Run("Sets", testSetsUpsert)

	t.Run("Tables", testTablesUpsert)
}
