# Development configuration
environment: development
app_name: "English AI"
version: "1.0.0"
debug: true

server:
  address: "localhost"
  port: 8888
  grpc_address: "localhost" 
  grpc_port: 50051
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  tls_enabled: false

database:
  host: "localhost"
  port: 5432
  name: "english_ai_dev"
  user: "postgres"
  password: "" # Set via environment variable
  ssl_mode: "disable"
  max_connections: 25
  max_idle_conns: 10
  conn_max_lifetime: "1h"
  conn_max_idle_time: "10m"

security:
  max_login_attempts: 5
  account_lockout_minutes: 15
  session_timeout: "24h"
  csrf_enabled: true
  cors_enabled: true
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://localhost:8888"
  require_https: false

password:
  min_length: 8
  max_length: 128
  require_uppercase: true
  require_lowercase: true
  require_numbers: true
  require_special: true
  special_chars: "!@#$%^&*()_+-=[]{}|;:,.<>?/"

pagination:
  default_size: 10
  max_size: 100
  limit: 1000

jwt:
  secret_key: "kIOopC3C7wA8DQH6FOF2Jfn+UZP8Q02nGxr/EgFMOmo="
  expiration_hours: 24
  refresh_token_expiration_days: 30
  issuer: "english-ai-dev"
  algorithm: "HS256"
  refresh_threshold: "2h"

email:
  verification_enabled: false
  verification_expiry_hours: 24
  require_verification: false
  smtp_host: "localhost"
  smtp_port: 1025
  from_address: "noreply@english-ai.dev"
  from_name: "English AI Development"
  templates:
    verification_template: "./templates/email/verification.html"
    welcome_template: "./templates/email/welcome.html"
    reset_password_template: "./templates/email/reset_password.html"

rate_limit:
  enabled: true
  per_minute: 60
  per_hour: 3600
  burst_size: 10
  window_size: "1m"

external_apis:
  anthropic:
    api_key: "dummy_key_for_dev"
    api_url: "https://api.anthropic.com"
    timeout: "30s"
    max_retries: 3
  quan_an:
    address: "localhost:8081"
    timeout: "10s"
    max_retries: 3

logging:
  level: "debug"
  format: "text"
  output: "stdout"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: false

# Global valid roles and statuses (applies to ALL environments)
valid_roles:
  - "admin"
  - "user"
  - "manager"
  - "guest"    # Added guest role from your original code

valid_account_statuses:
  - "active"
  - "inactive"
  - "suspended"
  - "pending"

# Domain-specific configuration
domains:
  enabled:
    - "account"
    - "branch"
    - "order"
    - "delivery"
    - "dish"
    - "table"
    - "guest"
    - "set"
    - "websocket"
    - "system"
    - "image"
  default: "system"
  
  account:
    max_login_attempts: 5
    password_complexity: true
    jwt_required: true
    
  branch:
    validation_required: true
    cache_enabled: true
    
  order:
    status_transitions: true
    websocket_notifications: true
    payment_validation: true
    
  delivery:
    real_time_tracking: true
    status_updates: true
    websocket_required: true
    
  websocket:
    jwt_validation: true
    message_size_limit: "1MB"
    connection_timeout: "30s"

# Error handling configuration
error_handling:
  include_stack_trace: true    # true for development
  sanitize_sensitive_data: false # false for development
  log_level: "debug"

---
# Production overrides (this section overrides above values in production)
environment: "production"

# Production-specific security
security:
  require_https: true
  max_login_attempts: 3  # Stricter in production

# Production error handling
error_handling:
  include_stack_trace: false
  sanitize_sensitive_data: true
  log_level: "info"

# Production logging
logging:
  level: "info"
  format: "json"

# Production can have different valid roles if needed
# valid_roles:
#   - "admin"
#   - "user"
#   - "manager"
#   # Note: No "guest" role in production

domains:
  account:
    max_login_attempts: 3  # Different from development