// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: quanqr/proto_qr/delivery/delivery.proto

package delivery

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeliveryService_CreateOrder_FullMethodName                   = "/delivery_proto.DeliveryService/CreateOrder"
	DeliveryService_GetDeliveryDetailById_FullMethodName         = "/delivery_proto.DeliveryService/GetDeliveryDetailById"
	DeliveryService_GetDeliveryDetailByClientName_FullMethodName = "/delivery_proto.DeliveryService/GetDeliveryDetailByClientName"
	DeliveryService_UpdateDelivery_FullMethodName                = "/delivery_proto.DeliveryService/UpdateDelivery"
	DeliveryService_GetDeliveriesListDetail_FullMethodName       = "/delivery_proto.DeliveryService/GetDeliveriesListDetail"
	DeliveryService_DeleteDeliveryDetailById_FullMethodName      = "/delivery_proto.DeliveryService/DeleteDeliveryDetailById"
)

// DeliveryServiceClient is the client API for DeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeliveryServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateDeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error)
	GetDeliveryDetailById(ctx context.Context, in *DeliveryIdParam, opts ...grpc.CallOption) (*DeliverResponse, error)
	GetDeliveryDetailByClientName(ctx context.Context, in *DeliveryClientNameParam, opts ...grpc.CallOption) (*DeliveryDetailedListResponse, error)
	UpdateDelivery(ctx context.Context, in *UpdateDeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error)
	GetDeliveriesListDetail(ctx context.Context, in *GetDeliveriesRequest, opts ...grpc.CallOption) (*DeliveryDetailedListResponse, error)
	DeleteDeliveryDetailById(ctx context.Context, in *DeliveryIdParam, opts ...grpc.CallOption) (*DeliveryIdParam, error)
}

type deliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryServiceClient(cc grpc.ClientConnInterface) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) CreateOrder(ctx context.Context, in *CreateDeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverResponse)
	err := c.cc.Invoke(ctx, DeliveryService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetDeliveryDetailById(ctx context.Context, in *DeliveryIdParam, opts ...grpc.CallOption) (*DeliverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverResponse)
	err := c.cc.Invoke(ctx, DeliveryService_GetDeliveryDetailById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetDeliveryDetailByClientName(ctx context.Context, in *DeliveryClientNameParam, opts ...grpc.CallOption) (*DeliveryDetailedListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryDetailedListResponse)
	err := c.cc.Invoke(ctx, DeliveryService_GetDeliveryDetailByClientName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) UpdateDelivery(ctx context.Context, in *UpdateDeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverResponse)
	err := c.cc.Invoke(ctx, DeliveryService_UpdateDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetDeliveriesListDetail(ctx context.Context, in *GetDeliveriesRequest, opts ...grpc.CallOption) (*DeliveryDetailedListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryDetailedListResponse)
	err := c.cc.Invoke(ctx, DeliveryService_GetDeliveriesListDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) DeleteDeliveryDetailById(ctx context.Context, in *DeliveryIdParam, opts ...grpc.CallOption) (*DeliveryIdParam, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryIdParam)
	err := c.cc.Invoke(ctx, DeliveryService_DeleteDeliveryDetailById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryServiceServer is the server API for DeliveryService service.
// All implementations must embed UnimplementedDeliveryServiceServer
// for forward compatibility.
type DeliveryServiceServer interface {
	CreateOrder(context.Context, *CreateDeliverRequest) (*DeliverResponse, error)
	GetDeliveryDetailById(context.Context, *DeliveryIdParam) (*DeliverResponse, error)
	GetDeliveryDetailByClientName(context.Context, *DeliveryClientNameParam) (*DeliveryDetailedListResponse, error)
	UpdateDelivery(context.Context, *UpdateDeliverRequest) (*DeliverResponse, error)
	GetDeliveriesListDetail(context.Context, *GetDeliveriesRequest) (*DeliveryDetailedListResponse, error)
	DeleteDeliveryDetailById(context.Context, *DeliveryIdParam) (*DeliveryIdParam, error)
	mustEmbedUnimplementedDeliveryServiceServer()
}

// UnimplementedDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryServiceServer struct{}

func (UnimplementedDeliveryServiceServer) CreateOrder(context.Context, *CreateDeliverRequest) (*DeliverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedDeliveryServiceServer) GetDeliveryDetailById(context.Context, *DeliveryIdParam) (*DeliverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeliveryDetailById not implemented")
}
func (UnimplementedDeliveryServiceServer) GetDeliveryDetailByClientName(context.Context, *DeliveryClientNameParam) (*DeliveryDetailedListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeliveryDetailByClientName not implemented")
}
func (UnimplementedDeliveryServiceServer) UpdateDelivery(context.Context, *UpdateDeliverRequest) (*DeliverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDelivery not implemented")
}
func (UnimplementedDeliveryServiceServer) GetDeliveriesListDetail(context.Context, *GetDeliveriesRequest) (*DeliveryDetailedListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeliveriesListDetail not implemented")
}
func (UnimplementedDeliveryServiceServer) DeleteDeliveryDetailById(context.Context, *DeliveryIdParam) (*DeliveryIdParam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeliveryDetailById not implemented")
}
func (UnimplementedDeliveryServiceServer) mustEmbedUnimplementedDeliveryServiceServer() {}
func (UnimplementedDeliveryServiceServer) testEmbeddedByValue()                         {}

// UnsafeDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryServiceServer will
// result in compilation errors.
type UnsafeDeliveryServiceServer interface {
	mustEmbedUnimplementedDeliveryServiceServer()
}

func RegisterDeliveryServiceServer(s grpc.ServiceRegistrar, srv DeliveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeliveryService_ServiceDesc, srv)
}

func _DeliveryService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeliverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).CreateOrder(ctx, req.(*CreateDeliverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetDeliveryDetailById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryIdParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDeliveryDetailById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDeliveryDetailById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDeliveryDetailById(ctx, req.(*DeliveryIdParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetDeliveryDetailByClientName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryClientNameParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDeliveryDetailByClientName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDeliveryDetailByClientName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDeliveryDetailByClientName(ctx, req.(*DeliveryClientNameParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_UpdateDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeliverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).UpdateDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_UpdateDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).UpdateDelivery(ctx, req.(*UpdateDeliverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetDeliveriesListDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDeliveriesListDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDeliveriesListDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDeliveriesListDetail(ctx, req.(*GetDeliveriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_DeleteDeliveryDetailById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryIdParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).DeleteDeliveryDetailById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_DeleteDeliveryDetailById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).DeleteDeliveryDetailById(ctx, req.(*DeliveryIdParam))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliveryService_ServiceDesc is the grpc.ServiceDesc for DeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "delivery_proto.DeliveryService",
	HandlerType: (*DeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _DeliveryService_CreateOrder_Handler,
		},
		{
			MethodName: "GetDeliveryDetailById",
			Handler:    _DeliveryService_GetDeliveryDetailById_Handler,
		},
		{
			MethodName: "GetDeliveryDetailByClientName",
			Handler:    _DeliveryService_GetDeliveryDetailByClientName_Handler,
		},
		{
			MethodName: "UpdateDelivery",
			Handler:    _DeliveryService_UpdateDelivery_Handler,
		},
		{
			MethodName: "GetDeliveriesListDetail",
			Handler:    _DeliveryService_GetDeliveriesListDetail_Handler,
		},
		{
			MethodName: "DeleteDeliveryDetailById",
			Handler:    _DeliveryService_DeleteDeliveryDetailById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quanqr/proto_qr/delivery/delivery.proto",
}
